id: P006685
initial_creation_type: ocr
source_metadata:
  id: bdr:W2PD17626
  title: '汉英－英汉藏学翻译词典

    '
  author: ''
  volumes:
    ebb9ac1437214ff4bfb0ba91bdf4137d:
      image_group_id: I4PD4265
      title: ''
      volume_number: 1
      total_pages: 1204
